In [2]:
import numpy as np
import time

In [312]:
def lab03_scp_aylwardg(A, c, k):
    #A- adjacency matrx(numpy array 2D, eg. A in section 4.1)
    #c- cost vector (numpy array)
    #k- number of times an element should be covered
    
    #initialization
    start_time = time.time()
    S = []
    Obj_cost = 0
    
    #Create covered array same size as A but all 0's
    Covered = A*0
    
    #while loop
    while(Covered.sum(axis = 1).min()<k):#check to see if the lowest value of covered is still <k
        #print("Not at full coverage")
        #initialize ticker and min_u_j
        i=0
        min_u_j = 1000
        
        for column in A.T:
            #Calculate number of uncovered elements by set j
            n_j= column.sum()
            
            #pop the right cost
            c_j = c[i]
            
            if n_j == 0:
                n_j = .0001
            
            #Calculate u_j
            u_j = c_j/n_j
            
            #Track and hold lowest u_j value
            if u_j < min_u_j:
                min_u_j = u_j
                #print("u_j = ", min_u_j)
                #track total cost
                current_c_j = c_j 
                #print("c_j = ", c_j)
                #Current set
                set_j = i
                #print("adding set index:", set_j)
                
            #move index for cost vector over by one
            i = i + 1    
            
        #select J that has minimum 
        S.append(A[:,set_j])
        Obj_cost = Obj_cost + current_c_j
          
        #Add current set to covered
        #print(A)
        Covered[:,set_j] = Covered[:,set_j]+A[:,set_j]
        #print("covered")
        #delete the selected column from A and its asociated cost
        
        A = np.delete(A, set_j, axis = 1)
        c = np.delete(c, set_j, axis = 0)
        #print("deleted")
        
        
    #x- Greedy solution
    x = S
    #Obj- Objective value of the greedy solution
    Obj = Obj_cost
    #Size- Number of selected sets in the greedy solution (int)
    Size = len(S)
    # Time- Computational time to run the greedy algorithm (float)
    Time = time.time()-start_time
    
    return x, Obj, Size, Time

In [320]:
#Input vars
A = np.array(
    [[1,0,0,1,0, 0, 1, 1, 0, 0],
     [0,1,1,0,1, 0, 1, 0, 2, 0], 
     [1,0,1,0,0, 2, 1, 1, 1, 1]])
c = np.array([3,2,1,4,5, 3, 1, 5, 1, 1])
k=4

In [321]:
#Testing
lab03_scp_aylwardg(A, c, k)

([array([1, 1, 1]),
  array([0, 2, 1]),
  array([0, 1, 1]),
  array([0, 0, 1]),
  array([1, 0, 1]),
  array([0, 0, 2]),
  array([0, 1, 0]),
  array([1, 0, 1]),
  array([1, 0, 0])],
 21,
 9,
 0.0017032623291015625)

In [315]:
x, Obj, Size, Time = lab03_scp_aylwardg(A, c, k)